# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ListUserGithub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ListUserGithub
pod 'Alamofire', '~> 5.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'RealmSwift', '~> 4.3.2'
pod 'SnapKit', '~> 4.0'
pod 'Firebase/Analytics'

end
